# Generated by Django 4.2.7 on 2023-11-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('campus', models.CharField(max_length=30)),
                ('previousEducation', models.TextField(max_length=300)),
                ('extracurricularActivities', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
            ],
        ),
    ]
