# Generated by Django 4.2.7 on 2023-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='confirm_password',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='apply',
            name='password',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
