# Generated by Django 4.2.7 on 2023-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_apply_confirm_password_alter_apply_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('occupation', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
