# Generated by Django 4.2.7 on 2023-12-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_professor_image_professor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(upload_to='static/profile1/images'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='slug',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
