# Generated by Django 4.2.7 on 2023-12-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_professor_image_alter_professor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(upload_to='static/profile1/images/professor'),
        ),
    ]
